
if(NOT DEFINED LOX_CCACHE)
	find_program(CCACHE_PROGRAM ccache)
	set(LOX_CCACHE ${CCACHE_PROGRAM} CACHE PATH "" FORCE)
	mark_as_advanced(LOX_CCACHE)
	unset(CCACHE_PROGRAM)
endif()


if(DEFINED LOX_CCACHE)
	if(LOX_SYSTEM MATCHES darwin)
		set(ENV{CCACHE_CPP2} true)
	endif()

	set(CMAKE_C_COMPILER_LAUNCHER   "${LOX_CCACHE}" CACHE PATH "" FORCE)
	set(CMAKE_CXX_COMPILER_LAUNCHER "${LOX_CCACHE}" CACHE PATH "" FORCE)
endif()
